### ISSUE TITLE
Media Library Assistant plugin throws warnings in admin

### ISSUE THREAD

**Issue by orionrush** [ResponsiveImagesCG/wp-tevko-responsive-images#131]
I encountered an issue today with the Media Library Assistant plugin. On the admin, thumbnails were generating warnings, from `tevkori_get_srcset_array`.

```
Warning: Illegal string offset 'sizes' in /html/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 165

Warning: Illegal string offset 'width' in /html/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 169

Warning: Illegal string offset 'height' in /html/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 170

Warning: Illegal string offset 'file' in /html/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 171

Warning: Illegal string offset 'file' in /html/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 173
```

I've yet to figure out why these jpgs in particular weren't returning results from `wp_get_attachment_metadata`, but the errors were there none the less. 

I wrote the plugin author as well: 
https://wordpress.org/support/topic/ricg-respoinsive-images-plugin-errors

**Comment by jaspermdegroot** [comment]
@orionrush 

The [first commit](https://github.com/orionrush/wp-tevko-responsive-images/commit/0a294756db80b6f29144b7b5ead44f54b346b528) of your PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/110 would make those warnings go away, right?

I am curious why/when ```wp_get_attachment_metadata``` doesn't return an array. Is this only a problem when you use the MLA plugin or could it also happen without this plugin? Only in the admin or also at the front-end?

In many cases an array with a width and height value (instead of a size name like 'thumbnail') is used as size parameter in the ```the_post_thumbnail``` calls in the admin. I wonder if that has something to do with it.

**Comment by joemcgill** [comment]
I agree, 0a29475 should solve the problem here. My guess is that some other plugin is filtering `wp_get_attachment_metadata`, which is odd, but we should probably throw in that sanity check rather than assume we're getting an array.
