### ISSUE TITLE
Include in srcset regardless of aspect ratio

### ISSUE THREAD

**Issue by ethanclevenger91** [ResponsiveImagesCG/wp-tevko-responsive-images#151]
In #48 (and likely elsewhere) there's talk of adding an argument to the various srcset functions to allow developers to explicitly declare which declared image sizes are used. I'd like to propose that in this case, the arguments also override the "with same aspect ratio" calculations - there may be situations in which a tall photo may be appropriate for desktop while a wide photo is more appropriate for mobile, and it would be nice to be get that result.

**Comment by jaspermdegroot** [comment]
This sounds more like a use case for the ```picture``` element, not for the ```srcset``` and ```sizes``` attributes.

**Comment by ethanclevenger91** [comment]
That was kind of my impression, but what exactly is the argument for that? Furthermore, is there a good WordPress solution for that? I wrote one a while back, but this is well-maintained and I saw a lot of arguments for images over pictures.

**Comment by peterwilsoncc** [comment]
@ethanclevenger91 `srcset` and  `picture` have very different use cases, the crib notes are:

`srcset`
This is intended for use by browsers developers rather than web developers/content creators. The same image is displayed at the best resolution for the browser, as decided by the browser. An image of taylor swift and her band will include her band in all browsers.

`picture`
This is intended for use by web developers and content creators for art direction. It allows for an image to be cropped differently for different resolutions. An image of tayor swift and her band may be crisp on large screens, but too small otherwise. The art-director may choose to crop it to taylor swift only for small screens to maintain detail, they use picture to do so.

There's a detailed comparison on Smashing Magazine http://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/.

**Comment by tevko** [comment]
Reason for closing as summed up by @jaspermdegroot. Thanks for your input @peterwilsoncc , please continue to contribute!

**Comment by ethanclevenger91** [comment]
Yeah, sorry for not following up, but that was really well explained and incredibly informative. Thanks for the information!
