### ISSUE TITLE
Docs: explain what Advanced Image Compression actually does

### ISSUE THREAD

**Issue by CaesarSchinas** [ResponsiveImagesCG/wp-tevko-responsive-images#152]
I can't find any info on what this option actually does.

Does it apply better compression than the WP defaults when uploading images?
Does it recompress existing images, or only new ones?
Does it convert images to WebP...?
Etc...

A brief description in the readme would be nice.

**Comment by joemcgill** [comment]
Hi @CaesarSchinas. Thanks for the feedback. I agree that we need to improve the docs here. In the mean time, the answer your questions are:

> Does it apply better compression than the WP defaults when uploading images?

Yes, this feature requires ImageMagick because it works by modifying the ImageMagick settings so the custom sizes produced by WP on upload are generated at a smaller file size.

> Does it recompress existing images, or only new ones?

It only compresses new images, but you can regenerate images using WP-CLI or a regeneration plugin in order to recompress older images.

> Does it convert images to WebP...?

This it does not do. Though, maybe room for an enhancement?

**Comment by joemcgill** [comment]
Related to #146

**Comment by CaesarSchinas** [comment]
Thanks @joemcgill.

I'm interested to know what compression is applied. Is it lossless or lossy? What settings are used in ImageMagick?

Of course I could look at the code, I suppose... :-)

**Comment by joemcgill** [comment]
The compression being applied are the settings @nwtn researched and explained in his recent [Smashing Magazine article](http://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/). By definition, the compression is lossy, but is designed to be "visually indistinguishable from Photoshop's [save for web...] output."
