### ISSUE TITLE
Filter out original sizes from custom crops from the media editor

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#155]
It is possible in the media editor to create an art-directed crop of an image, while maintaining the same aspect ratio as the original file. If that happens, we end up including both the original and the cropped versions in the `srcset` list, which can lead to unintentional consequences.

Examples of the same image at different viewport widths when the `srcset` includes custom crops along side the original image.
https://cloudup.com/cnDz1ekRWaM
https://cloudup.com/cOT_TQBvq6c

It's possible that we could look for the inclusion of the same 14 character hash that WP would include in any cropped image size, and only match sources that also include the same hash, but I'm open to other suggestions as well.

**Comment by tevko** [comment]
Would this be better as an option, rather than default behavior? I imagine some users may want custom crops to be a part of their sourceset

**Comment by joemcgill** [comment]
No, I think it should be default, because you really shouldn't be using
'srcset' to do art direction.

**Comment by jaspermdegroot** [comment]
I did some investigation to understand what's going on. When you edit an image the meta data of the original image is stored in ```_wp_attachment_backup_sizes``` while ```_wp_attachment_metadata``` contains the data of the edited (cropped) image. The problem is that when an image size can't be recreated  because the edited image became smaller than that image size, this image size will still be in ```_wp_attachment_metadata``` but it's the original image.

Let's say the original image is bigger than image size "large", but the edited image is smaller. When you open the image editor and use the dropdown menu to select a different image size for your post, you will see that "thumbnail", "medium", and "full" show the edited image, but "large" shows the original image. I think that in this case image size "large" shouldn't be available anymore after editing and consider this a bug in WP core, but maybe others think different about that.

I think the approach used in PR https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/161 is the best way to fix the problem for now.

**Comment by joemcgill** [comment]
You found the exact same thing I found. I attempted to play with a solution that would filter out any images found in the image post's `_wp_attachment_backup_sizes` meta field, but ran into the issue you described with the old large size still hanging around. Whether that is a bug or not is debatable (some may see this as a feature) but we could file a ticket and see what shakes out.

For now I'm going to clean up #161 and we can go with that approach.
