### ISSUE TITLE
Some streamlining / code consolidation

### ISSUE THREAD

**Issue by azaozz** [ResponsiveImagesCG/wp-tevko-responsive-images#187]
Looking at `_tevkori_filter_content_images_callback()` and `tevkori_get_srcset_array()`, seems the latter will be better off without default size, and the former doesn't need to call `wp_get_attachment_metadata()` which is called again in the later. If `$size` is empty in `tevkori_get_srcset_array()`, it can probably do https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/blob/dev/wp-tevko-responsive-images.php#L392.

This may not make big difference, but the image's width and height for a particular `$size` can be wrong. The "real" are set with the width and height attributes in the actual img tag. This happens for all images that have been "soft-resized" in the Visual editor. The image dimensions that were returned for a particular image "size name" (like thumbnail, medium, etc.) can be quite different from the dimensions of the displayed image.

In that terms, perhaps the width and height that are set in the img tag should always have a priority over the "size name" passed in the class. Even better if the size name is discarded completely and the size at which the image is going to be displayed is matched by using only `wp_get_attachment_metadata()` and the width/height from the tag. This will need some calculations, but should be faster, as the only data needed from the DB will be the attachment meta.

**Comment by azaozz** [comment]
For the same reasons, maybe drop `$img = image_downsize( $id, $size )` from `tevkori_get_sizes()`. 

Also, generally it is good to use existing API functions. However in this case using the existing image size manipulation functions may not be such a good idea. They are mostly for use in the admin or when uploading images. Many plugins use the hooks there and some may be running expensive/slow code with the perception the hooks will never be run on the front-end.

**Comment by joemcgill** [comment]
We can probably avoid calling  `image_downsize` in `tevkori_get_sizes()` by letting the second parameter accept an array corresponding to the image height and width in pixels. For our default implementation, we really only need to know the image width in order to build the `sizes` string.

In practice, I wonder if we even need a helper function for building the `sizes` attribute or if we could simplify this by creating our default `sizes` attribute directly in `tevkori_filter_attachment_image_attributes()` and `_tevkori_filter_content_images_callback()`?

**Comment by joemcgill** [comment]
In #194, I've eliminated the need to hit `image_downsize()` in our display filter by passing the image width directly to `tevkori_get_sizes()` using the `$args` parameter.

> seems [ `tevkori_get_srcset_array()` ] will be better off without default size

The intent here was to mimic the other media functions people use to build their own image markup patterns on the front end. 

For example:
```
if ( $img_id = get_field('custom_image') ) {
    $srcset = tevkori_get_srcset_string( $img_id, 'full' );
    echo "<img alt='$alt' srcset='$url' sizes='100vw' />
}
````

I do think it may make more sense to default to 'medium' rather than 'thumbnail', since 'thumbnail is normally a hard crop and would only return a single source in most cases (see #192).

> This may not make big difference, but the image's width and height for a particular $size can be wrong. The "real" are set with the width and height attributes in the actual img tag.

In most cases, this shouldn't be a problem because we're going to end up returning all the sizes that match the aspect ratio anyway.

**Comment by joemcgill** [comment]
I'm going to leave this open, but remove it from the current milestone, because there's more we can do here around avoiding superfluous calls to internal image functions once we've already grabbed all the data we need.

**Comment by joemcgill** [comment]
Closing this now that the main functions [have been merged](https://github.com/WordPress/WordPress/commit/99be7beda000d7466779910edb243e136316726a) into core. Further improvements can get their own tickets.
