### ISSUE TITLE
Add lazyloading

### ISSUE THREAD

**Issue by oskarrough** [ResponsiveImagesCG/wp-tevko-responsive-images#20]
Would you be open to include an option to lazy load images? Basically it would require these changes:

- add `class="lazyload"`
- change `src` to `data-src`
- set `sizes="auto"`
- include https://github.com/aFarkas/lazysizes script
- option to switch picturefill for https://github.com/afarkas/respimage (not sure whether this is needed)

ping @afarkas

**Comment by tevko** [comment]
Hey @oskarrough thanks for contributing. I think this is out of scope concerning the main intention of this plugin, which is to provide automatic responsive images

**Comment by aFarkas** [comment]
Lazyloading and/or automatic sizes calculation would be indeed nice. I think especially the automatic sizes calculation would be nice. Some notes to the above:

* it should be ``data-sizes="auto"`` not ``sizes="auto"``
* a switch from picturefill to respimage is not needed (respimage is only needed in case you want to also use [the optimumx extension](https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/optimumx), because picturefill has no API to re-parse the ``srcset`` attribute in Safari)

Something in general it would be also nice to have those scripts as last async scripts in the head instead of bottom of body.

Another nice to have feature would be an option so that wp automatically renders the markup for [intrinsic ratio including the padding-bottom/padding-top value](http://www.mademyday.de/css-height-equals-width-with-pure-css.html).

**Comment by aFarkas** [comment]
@tevko 
Actually this is a little bit sad. lazySizes is not just a lazyloader but also an integration helper to get the value of the ``sizes`` attribute right. Sometimes it is either hard or not the right way to declare the sizes attribute in the backend and should be done in the frontend. lazysizes is the only script I know of, which makes the later possible.

**Comment by aFarkas** [comment]
@oskarrough 
I just made a small plugin: https://github.com/aFarkas/wp-lazysizes
Note: for srcset support you still need this plugin.

**Comment by oskarrough** [comment]
Beautiful! Will definitely use this. Thank you.
