### ISSUE TITLE
Warning in mediaview for non-images

### ISSUE THREAD

**Issue by tobaco** [ResponsiveImagesCG/wp-tevko-responsive-images#208]
I get the following warning for non-image media (e.g. svg, doc)

> Warning: Illegal string offset 'width' in /www/htdocs/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 190
> 
> Warning: Illegal string offset 'height' in /www/htdocs/wp-content/plugins/ricg-responsive-images/wp-tevko-responsive-images.php on line 191

Seems related to this bug #153 

i couldn't find the fix in the sourcecode anymore.

**Comment by jaspermdegroot** [comment]
@tobaco 

Thanks for reporting the issue. The problem was fixed before but we made a lot of big changes in the code and this is a regression.

**Comment by jaspermdegroot** [comment]
@tobaco 

You can make the following changes in wp-tevko-responsive-images.php to fix the problem.

line 187:
```
if ( ! is_array( $img_meta = wp_get_attachment_metadata( $id ) ) ) {
	return false;
}
```

line 397:
```
if ( ! $size && ! empty( $id ) && is_array( $meta = wp_get_attachment_metadata( $id ) ) ) {
```

**Comment by tobaco** [comment]
Thanks! Seems to work!

**Comment by jaspermdegroot** [comment]
@tobaco 

We just released version 3.0.0 of the plugin. Since we made major changes in the code, the fix as I posted here was not applicable anymore. We did keep the problem in mind though, so I think issue shouldn't occur anymore but I wanted to ask you to confirm after you updated to 3.0.

@grappler @djcowan You reported the same problem in #153 and #133 before. Can you test as well?

Note that 3.0 uses the same code as we implemented in WordPress core for the upcoming 4.4 release. So if you have a 4.4 beta or nightly build WordPress installation you could also test without this plugin.

Thanks!

**Comment by grappler** [comment]
@jaspermdegroot I got the following error when uploading a svg image. Running WP 4.4-beta3-35569

`Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /wp-includes/media.php:209 Stack trace: #0 /wp-includes/media.php(753): image_downsize(2231, 'thumbnail') #1 /wp-admin/async-upload.php(61): wp_get_attachment_image_src(2231, 'thumbnail', true) #2 {main} thrown in /wp-includes/media.php on line 209`

**Comment by jaspermdegroot** [comment]
@grappler - Thanks for your reply. We are going to look into it.

**Comment by joemcgill** [comment]
I'm not able to reproduce the SVG upload error @grappler described using 4.4-beta4-35636 and version 3.0.0 of the plugin nor the latest code in `dev`. Additionally, the Stack trace doesn't include any reference to any of the responsive image functions, so I don't think this is an issue on our end. I'm going to close for now, and we can reopen if anyone can add the steps to reproduce.
