### ISSUE TITLE
Pagespeed Insights penalty

### ISSUE THREAD

**Issue by ichik** [ResponsiveImagesCG/wp-tevko-responsive-images#69]
I've done some testing with single article: http://sequencebreak.ru/apotheon/ Images are displayed correctly, and according to Safari inspection correctly small images are loaded on mobile: http://take.ms/8fbiX
However, Pagespeed Insights still reports that 2 images can be greatly reduces by scaling and optimising: https://developers.google.com/speed/pagespeed/insights/?url=sequencebreak.ru%2Fapotheon%2F. Since they're optimised really (I use EWWW) I think scaling is what PI suggests. Funny enough it doesn't notice unscaled featured image inserted via CSS background btw.
Is there any reasonable way to avoid this Insights penalty (it affects PageRank, yada, yada)?

**Comment by joemcgill** [comment]
HI @ichik,

In order to avoid scaling, you'll need to create the specific image sizes that you need for your layout. In your particular case, it looks like creating another image size around 650px wide may be a good idea since many mobile screens are around 320–370px wide with a pixel density around 2x. To add an image size you'll need to do something like this in the functions.php file of your theme:

`add_image_size( 'my-image-size`, 650 );`

You'll need to regenerate thumbnails in order for this new size to be applied to existing images, but it should work for new images going forward.

Hope this helps.
- Joe

**Comment by ichik** [comment]
Yep, I've added more sizes to the mix, specifically the 320, 480 and 640. Insights now loads 640 one, but still penalises score heavily (93% reduction it says).
I assume that's a bug on their side.

**Comment by joemcgill** [comment]
It may be, but one thing to keep in mind is that this plugin doesn't affect the compression settings for your image when it's resized by WordPress. You may want to look into a plugin that specifically improves image compression in order to avoid that penalty. This one: https://wordpress.org/plugins/ewww-image-optimizer/ might do the trick.

**Comment by ichik** [comment]
Images are compressed, that's for certain. I actually use exactly the mentioned plugin, and forced re-optimising after regenerating thumbnails.

**Comment by ichik** [comment]
After digging a bit deeper I discovered that PI would gladly accept the following code (though it works exactly the same as current one):
`<picture>
    
    <source  srcset="https://cdn.domain.nl/image-940x260.png" media="(min-width: 960px)">
    <source  srcset="https://cdn.domain.nl/image-700x194.png" media="(min-width: 768px)">
    <source  srcset="https://cdn.domain.nl/image-440x122.png" media="(min-width: 480px)">
    <source  srcset="https://cdn.domain.nl/image-280x77.png">
    
    <img srcset="https://cdn.domain.nl/image-940x260.png" class="aligncenter size-full wp-image-2310 nolazy" alt="dermaroller 540">
    <noscript><img src="https://cdn.domain.nl/image-940x260.png" class="nolazy"></noscript>
</picture>`

**Comment by side777** [comment]
img src only inside noscript, that's what i suggested in #63 - images are loading twice / wrong sizes first on some mobile browsers. ^^ this would solve this issue too... maybe it's even the reason for the penalty, after all?
