### ISSUE TITLE
RICG (v 2.2.1) not working on Chrome (41)

### ISSUE THREAD

**Issue by JetLewis** [ResponsiveImagesCG/wp-tevko-responsive-images#76]
Hello,
The plugin seems to work fine on every browser but Chrome.
Basically, the src of the img keep being the full-size image instead of changing according to the window size, which is pretty problematic. The width attribute doesn't seem to show up either. Seems like a JS issue ( or maybe Picturefill 2.3 ?) , but I can't find a callback to test the issue.

Thanks in advance.
Jet

**Comment by joemcgill** [comment]
Hi Jet,

Thanks for reporting this issue. One thing to keep in mind is that Chrome has native support for `srcset` and `sizes` and as such, doesn't depend on the polyfill for this behavior. Additionally, you may be running into one of the expected behaviors in the way Chrome handles choosing larger images that are in cache over a smaller image from a source list in order to avoid an extra request. See this related issue: https://github.com/scottjehl/picturefill/issues/435

Can you check to see if the correct image is loaded on smaller screens after disabling your cache (or from an incognito session?

Thanks,
Joe

**Comment by JetLewis** [comment]
Hi Joe, 

It still displays the default image on smaller screens with cache disabled. mhh
Anyway, I'll close the topic as it looks like a Chrome issue as depicted in the related issue you mentioned and not a bug from the plugin.

Thanks a lot,
Jet

**Comment by timocouckuyt** [comment]
Has anybody found a workaround for this?

**Comment by jaspermdegroot** [comment]
@JetLewis @timocouckuyt - I tested this on Chrome 42 / OS X (with retina screen) and can't reproduce the issue.

**Comment by timocouckuyt** [comment]
@jaspermdegroot OK :-) But it also seems that the Pagespeed insight tool isnt scanning the srcset and sizes attribute either. Using the picture element gets read fine, tho.
