### ISSUE TITLE
Double download in Safari

### ISSUE THREAD

**Issue by joemcgill** [ResponsiveImagesCG/wp-tevko-responsive-images#78]
Reported in the WordPress.org support forum: https://wordpress.org/support/topic/safari-loads-biggest-available-size?replies=4

>I'm having trouble to get this plugin working on Safari (Mac OS and iOS latest versions). The browser displays the correct size, but the biggest available size (the original uploaded file pic.jpg) will be downloaded also (as seen in the timeline). The cache is clear. Chrome, FF are working perfectly.

Follow up comment:

> I've figured out the same problem at the official picturefill demo sites.
>
>Possible solution: As Safari doesn't fully support the srcset Attribute yet, it falls back to src. So Safari always downloads the "fallback" version (in this case the full resolution image) and the appropriate image.
>
>Any feedback is welcome!
>
>Also I suggest to omit the fallback src attribute, as described by scott jehl http://www.filamentgroup.com/lab/to-picturefill.html

Should we consider removing the `src` attribute or is there a better workaround since Scott wrote that article?

**Comment by tevko** [comment]
I don't know, if it's only an issue in one browser, it seems unfair to penalize all others by removing the src attribute

**Comment by joemcgill** [comment]
There are definitely trade offs. On one hand, it seems that any browser that doesn't support `srcset` will automatically download the src file and may download a second from the srcset list.

It looks like the folks at The Guardian are omitting the src attribute on at least some of their implementations of responsive image: https://twitter.com/patrickhamann/status/577831047964028928

Here's an example of the output of one of their images from their [developer blog](http://www.theguardian.com/info/developer-blog) when I load it in Safari:

```
<img class="responsive-img" srcset="" sizes="(min-width: 980px) 470px, (min-width: 740px) 350px, 127px" src="http://i.guim.co.uk/static/w-470/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171301/6242015734_f2523a1d1e_o-540x324.jpeg" data-pfsrcset="//i.guim.co.uk/static/w-470/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171301/6242015734_f2523a1d1e_o-540x324.jpeg 470w, //i.guim.co.uk/static/w-350/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489172258/6242015734_f2523a1d1e_o-380x228.jpeg 350w, //i.guim.co.uk/static/w-127/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171462/6242015734_f2523a1d1e_o-140x84.jpeg 127w">
```

However, on article pages they still show the src element, which is causing a double download in Safari:

```
<img src="http://i.guim.co.uk/static/w-700/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171718/6242015734_f2523a1d1e_o-1020x612.jpeg" srcset="" sizes="(min-width: 980px) 620px, (min-width: 740px) 700px, (min-width: 660px) 620px, (min-width: 480px) 645px, 465px" class="maxed responsive-img" itemprop="contentURL representativeOfPage" alt="Our in-house training focuses on peer to peer learning" data-pfsrcset="//i.guim.co.uk/static/w-620/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489172502/6242015734_f2523a1d1e_o-620x372.jpeg 620w, //i.guim.co.uk/static/w-700/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171718/6242015734_f2523a1d1e_o-1020x612.jpeg 700w, //i.guim.co.uk/static/w-645/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171718/6242015734_f2523a1d1e_o-1020x612.jpeg 645w, //i.guim.co.uk/static/w-465/h--/q-95/sys-images/Guardian/Pix/pictures/2015/2/9/1423489171301/6242015734_f2523a1d1e_o-540x324.jpeg 465w">
```

We could explore ways of filtering out the src attribute but we want to make sure not to save markup in content without the src attribute.

**Comment by tevko** [comment]
I'm of the opinion that leaving the src attribute off has too many trade offs. Perhaps we could add a flag that removes the src attribute if the developer wants, but other than that, there are too many side effects caused when we force the plugin to leave it out

**Comment by joemcgill** [comment]
I think we would need a patch in order to evaluate the tradeoffs properly. The question is what would a potential fix would look like, i.e., what requirements would it have to hit in order to be merged?

**Comment by jaspermdegroot** [comment]
Maybe it's an idea to add a ```data-``` attribute to images, with the smallest image from the ```srcset``` as value. Then add a regex to the ```the_content``` filter to replace the ```src``` value by the one from the ```data-``` attribute. Browsers that don't support ```srcset``` will still load the ```src``` image, but at least it's a small one. I think it's better than removing the ```src``` attribute, because it still serves an image in case of no JavaScript (like some search engines and social networks that don't support ```srcset``` yet).

I do this in my project where I also use [lazysizes](https://github.com/aFarkas/lazysizes) so I can use the ```src``` image as "low quality image placeholder". Works great.

**Comment by joemcgill** [comment]
Do you have any example code you could share @jaspermdegroot?

**Comment by passij** [comment]
Are there an other known trade offs despite the ones mentioned in the article? I get the concerns. But I think there are no real options. 

If the src attribute stays, why polyfilling at all? Browsers which doesn't natively Support responsive images are loading  images twice because of the src. So its even worse using the polyfill.

**Comment by joemcgill** [comment]
The main concern I think we would need to keep in mind is how this would work with content images since that markup gets saved in the database. We definitely can't strip the `src` attribute off there, so we would need to filter it as @jaspermdegroot suggests. If we can come up with a non-destructive solution, I'd be interested.

**Comment by Wilto** [comment]
@jaspermdegroot! Long time no see!

Man, this is a tough one. The double-download comes in browsers that support `srcset` in some form but _not_ the full responsive images spec, so Picturefill still ends up in play (hence iOS being an issue). This happened with a few versions of Chrome as well, but y’know, evergreen.

We settled on this approach because it meant a double-download in a finite set of browsers: those versions of Chrome are long gone, and the upgrade cycle on iOS is crazy aggressive—so once a version of Safari with full respimg support appears, the double download will go away entirely. Using `src` meant double downloads for any and all older browsers, which wasn’t something we were comfortable recommending—and trying to work around this in prefetching browsers basically puts us in the same situation we were in back when we started the Quest for Responsive Images.

Now, an empty `src` _is_ valid, but this is further complicated by [how weird browsers get about omitted `src` values](http://wilto.github.io/srcn-polyfills/).

All that said: giving up the `src` fallback pattern _kills_ me. So. 

Hm.

**Comment by scottjehl** [comment]
There may be no perfect answer to this one, but it may make sense to specify `src` if the browsers that prefetch images (before JS can swap the src for something else) are supporting respimg natively nowadays anyhow. Some research into how successful JS-based src swapping is across non-respimg browsers (does it make 1 or 2 requests?) would be super helpful here.

That aside, I think a reasonable alternative to omitting `src` altogether is to reference your smallest image size via `src`; in the case of a wasted request, at least it'll be lightweight. That small size will often end up being the size that many small screen devices need too, so it may end up making one request in devices that most frequently operate in constrained network conditions. Of course, large screen devices often browse with network/data constraints as well, so it's imperfect. 

Some folks argue that a small (to-be-replaced) initial image can provide a desirable "progressive" render as well, so that's something to test.

I like the guardian's approach too. They've chosen to define `src` in key image placements that need to render asap. That flexibility to choose how to use it is pretty nice, if possible.

**Comment by jaspermdegroot** [comment]
Hey @Wilto and @scottjehl! Missed you guys! :)

@joemcgill - I created a PR (https://github.com/ResponsiveImagesCG/wp-tevko-responsive-images/pull/79) to show how I replace the ```src``` by the smallest from the ```srcset```.

**Comment by tevko** [comment]
@Wilto @scottjehl thanks for weighing in guys. Scott I think your approach is definitely the most reasonable. @joemcgill thoughts?

**Comment by side777** [comment]
The developers already have the option to remove the src attribute by filtering the_content. It's totally in their hands. 

But please keep in mind it's not only one old browser. It's almost any browser in combination with lazy loading (#63), and we still get a pagespeed penalty for double loading (#69). 

I'm already testing a possible solution: wrapping the src in a noscript block in a the_content filter. I don't see any tradeoffs and it's working. Polyfill adds the src for incompatible browsers instead of switching it (too late, << that's causing the double loading). The database stays untouched.

Another solution would be to use the medium image as a fallback and check if it's already loaded before switching the src at polyfill's end. 

Mobile devices don't always use the smallest image anymore, these days are over... So the smallest img solution would very likely lead to wasted downloads on most modern mobile devices. Wasted data AND the google penalty is not acceptable.

**Comment by joemcgill** [comment]
@scottjehl thanks for the input. I do think there may be some merit in choosing a smaller `src` when needed to make the double download (if necessary) as small as possible. 

While I think we should explore the possibility of the noscript method that @side777 suggests, I suspect we're going to run into some edge cases if we try rewriting the HTML that drastically before the page renders. If this was always going to be a standalone plugin, that wouldn't bother me as much, but remember that we're looking for solutions that could be merged into core. Rewriting (or even filtering) all images to a pattern that omits a `src` attribute and uses a `<noscript>` fallback would probably be a non-starter.

As I understand it, this issue should only affect browsers that have partial support for `srcset` (i.e., Safari and possibly Microsoft's upcoming [Spartan browser](http://ircbot.responsiveimages.org/bot/log/respimg/2015-04-01#T122198), so until the Picturefill team comes up with a different solution for polyfilling that functionality, we should start by figuring out which browsers are currently being penalized and find the most graceful way of handling the double download without burdening everyone else and adding cruft to the markup.

**Comment by joemcgill** [comment]
@jaspermdegroot thanks for the PR example. I'll take a look soon (though I'm more interested in getting your gallery code PR in first :wink:)

**Comment by side777** [comment]
> this issue should only affect browsers that have partial support for srcset

+ some mobile browsers. and the google penalty is not browser specific.

**Comment by joemcgill** [comment]
Here's a test case to compare what we're doing now vs. a no-src solution (without a noscript fallback): http://codepen.io/joemcgill/full/JoVVBv/

**Comment by passij** [comment]
thanks for this great discussion! looking forward to the solution. if there's a way (for a non plugin developer) to help, let me know.

**Comment by joemcgill** [comment]
Not sure how quickly Webkit is moving things from nightlies into production, but now that the nightlies have support for both `srcset` with `w` descriptors and `sizes` this is closer to being able to resolve itself. In the mean time, we could use @jaspermdegroot's approach in #93 for images that are being generated dynamically, but we may want to be careful about changing the user's intended `src` for content images for now.

**Comment by tevko** [comment]
For now we're going to close this issue. WebKit nightly has full support and hopefully it won't be too long before double downloading is a thing of the past. Until then, we'll pick up this discussion when it comes time for us to merge into WordPress core
